### ISSUE TITLE
multiply function suffers with remotely large numbers

### ISSUE THREAD

**Issue by mlissner** [2degrees/docker-solr4#1]
It appears that even on my 64 bit machine (the one that's part of this dockerfile, I believe):

```
solr@80bb85b5d372:/$ uname -a 
Linux 80bb85b5d372 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
```

The multiply function in solr.sh operates on a 32 bit awk:

```
solr@80bb85b5d372:/$ multiply 4000000000 2
2147483647
```

If that number doesn't ring a bell, see: https://en.wikipedia.org/wiki/2,147,483,647#In_computing

This means that the `-xmx` setting peaks out at about 2GB. Lovely!

**Comment by mlissner** [comment]
This works btw:

```
function multiply() {
    # Multiply two numbers. Easy, right? Except awk can sometimes be 32 bit,
    # making it only go up to about 2GB of bytes, bash can only multiply ints,
    # and bc can neither convert floats to ints nor strip newlines.
    local x="$1"
    local y="$2"
    local result=$(echo "$x * $y" | bc | tr -d '\n')
    echo -n ${result%.*}
}
```

(though you also need to install `bc` in the build.sh script.)

**Comment by franciscoruiz** [comment]
Hi Mike, thanks for reporting this issue. I'm afraid this project is no longer maintained (I'll flag it as such), so feel free to fork it and apply your suggested changes.

**Comment by mlissner** [comment]
Fair enough. It did help me quite a bit, and I've got my version over on freelawproject/courtlistener-solr-server.
